services:
  - type: web
    name: textmood-dj-backend
    env: python
    plan: free
  # run commands from the `backend` directory (monorepo support)
  root: backend
  buildCommand: pip install -r requirements.txt
  startCommand: bash start.sh
